-- Migration 0001 commented out to sync with existing DB state
-- CREATE TABLE "education_institutions_minedu" (
-- 	"codigo_modular" text PRIMARY KEY NOT NULL,
-- 	"nombre" text NOT NULL,
-- 	"nivel" text NOT NULL,
-- 	"tipo_gestion" text,
-- 	"departamento" text,
-- 	"provincia" text,
-- 	"distrito" text,
-- 	"direccion" text,
-- 	"estado" text DEFAULT 'Activo'
-- );
-- --> statement-breakpoint
-- ALTER TABLE "institutions" ADD COLUMN "codigo_modular" text;--> statement-breakpoint
-- ALTER TABLE "institutions" ADD COLUMN "nivel" text;--> statement-breakpoint
-- CREATE INDEX "idx_ie_minedu_nivel" ON "education_institutions_minedu" USING btree ("nivel");--> statement-breakpoint
-- CREATE INDEX "idx_ie_minedu_departamento" ON "education_institutions_minedu" USING btree ("departamento");--> statement-breakpoint
-- CREATE INDEX "idx_ie_minedu_nombre" ON "education_institutions_minedu" USING btree ("nombre");--> statement-breakpoint
-- CREATE INDEX "idx_institution_codigo" ON "institutions" USING btree ("codigo_modular");