-- CREATE TABLE "resource_templates" (
-- 	"id" text PRIMARY KEY NOT NULL,
-- 	"institution_id" text,
-- 	"category_id" text,
-- 	"name" text NOT NULL,
-- 	"icon" text,
-- 	"default_brand" text,
-- 	"default_model" text,
-- 	"is_default" boolean DEFAULT false,
-- 	"sort_order" integer DEFAULT 0,
-- 	"created_at" timestamp DEFAULT now()
-- );
-- --> statement-breakpoint
-- ALTER TABLE "resources" ADD COLUMN "template_id" text;--> statement-breakpoint
-- ALTER TABLE "resources" ADD COLUMN "internal_id" text;--> statement-breakpoint
-- ALTER TABLE "resource_templates" ADD CONSTRAINT "resource_templates_institution_id_institutions_id_fk" FOREIGN KEY ("institution_id") REFERENCES "public"."institutions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- ALTER TABLE "resource_templates" ADD CONSTRAINT "resource_templates_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
-- CREATE INDEX "idx_template_category" ON "resource_templates" USING btree ("category_id");--> statement-breakpoint
-- CREATE INDEX "idx_template_institution" ON "resource_templates" USING btree ("institution_id");--> statement-breakpoint
-- ALTER TABLE "resources" ADD CONSTRAINT "resources_template_id_resource_templates_id_fk" FOREIGN KEY ("template_id") REFERENCES "public"."resource_templates"("id") ON DELETE no action ON UPDATE no action;