export const DEFAULT_TEMPLATES: Record<string, { name: string; icon: string }[]> = {
    'Mantenimiento': [
        { name: 'Herramientas', icon: '🔧' },
        { name: 'Repuestos', icon: '⚙️' },
        { name: 'Limpieza', icon: '🧹' },
        { name: 'Insumos', icon: '📦' },
        { name: 'Otros', icon: '📌' },
    ],
    'Equipos Portátiles': [
        { name: 'Laptop', icon: '💻' },
        { name: 'Tablet', icon: '📱' },
        { name: 'Chromebook', icon: '📓' },
    ],
    'Componentes PC': [
        { name: 'Monitor', icon: '🖥️' },
        { name: 'Teclado', icon: '⌨️' },
        { name: 'Mouse', icon: '🖱️' },
        { name: 'CPU', icon: '🖥️' },
    ],
    'Periféricos': [
        { name: 'Audífonos', icon: '🎧' },
        { name: 'Micrófono', icon: '🎤' },
        { name: 'Cámara Web', icon: '📷' },
        { name: 'Parlantes', icon: '🔊' },
    ],
    'Cables y Conectores': [
        { name: 'HDMI', icon: '🔌' },
        { name: 'VGA', icon: '🔌' },
        { name: 'USB', icon: '🔌' },
        { name: 'Red (RJ45)', icon: '🌐' },
        { name: 'Alimentación', icon: '⚡' },
    ],
    'Displays y Multimedia': [
        { name: 'Proyector', icon: '📽️' },
        { name: 'Televisor', icon: '📺' },
        { name: 'Pizarra Interactiva', icon: '📟' },
        { name: 'Pantalla', icon: '🖥️' },
    ],
    'Red e Infraestructura': [
        { name: 'Router', icon: '📡' },
        { name: 'Switch', icon: '🖧' },
        { name: 'Access Point', icon: '📶' },
        { name: 'Servidor', icon: '🗄️' },
        { name: 'Firewall', icon: '🧱' },
    ],
    'Almacenamiento': [
        { name: 'Disco Duro', icon: '💽' },
        { name: 'SSD Externo', icon: '💾' },
        { name: 'Memoria USB', icon: '🖊️' },
        { name: 'NAS', icon: '🗄️' },
    ],
    'Protección Eléctrica': [
        { name: 'UPS', icon: '🔋' },
        { name: 'Estabilizador', icon: '⚡' },
        { name: 'Regleta Multicontacto', icon: '🔌' },
    ],
    'Mobiliario': [
        { name: 'Escritorio', icon: '🪑' },
        { name: 'Silla', icon: '🪑' },
        { name: 'Archivador', icon: '🗄️' },
        { name: 'Mesa', icon: '🪑' },
        { name: 'Pizarra', icon: '📝' },
    ],
    'Software y Licencias': [
        { name: 'Sistema Operativo', icon: '💽' },
        { name: 'Antivirus', icon: '🛡️' },
        { name: 'Diseño Gráfico', icon: '🎨' },
        { name: 'Paquete de Ofimática', icon: '📄' },
    ],
    'Streaming y Producción': [
        { name: 'Capturadora', icon: '📼' },
        { name: 'Iluminación', icon: '💡' },
        { name: 'Consola de Audio', icon: '🎛️' },
    ],
    'Kits Educativos': [
        { name: 'Kit de Robótica', icon: '🤖' },
        { name: 'Microscopio', icon: '🔬' },
        { name: 'Material de Laboratorio', icon: '🧪' },
    ],
    'Presentación': [
        { name: 'Puntero Láser', icon: '🖍️' },
        { name: 'Papelógrafo', icon: '📋' },
        { name: 'Atril', icon: '🎤' },
    ],
    'Seguridad Física': [
        { name: 'Cámara de Seguridad', icon: '📹' },
        { name: 'Lector Biométrico', icon: '👆' },
        { name: 'Alarma', icon: '🚨' },
    ],
};
