import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import { educationInstitutionsMinedu } from './src/database/schema';
import { ilike, and, or } from 'drizzle-orm';

const pool = new Pool({
    connectionString: "postgresql://postgres:postgres@localhost:5432/flip-v2"
});
const db = drizzle(pool);

async function check() {
    console.log("Searching for 'gran unidad'...");

    // Test the exact query generated by the service
    const q1 = "gran unidad";

    const res1 = await db.select({
        codigoModular: educationInstitutionsMinedu.codigoModular,
        nombre: educationInstitutionsMinedu.nombre,
    })
        .from(educationInstitutionsMinedu)
        .where(or(
            ilike(educationInstitutionsMinedu.nombre, `%${q1}%`),
            ilike(educationInstitutionsMinedu.codigoModular, `%${q1}%`)
        ))
        .limit(10);

    console.log(`Results for exact '%${q1}%':`, res1.length);
    if (res1.length > 0) console.log(res1);

    // Try treating spaces differently
    const qParts = q1.split(' ');
    const andConditions = qParts.map(p => ilike(educationInstitutionsMinedu.nombre, `%${p}%`));

    const res2 = await db.select({
        codigoModular: educationInstitutionsMinedu.codigoModular,
        nombre: educationInstitutionsMinedu.nombre,
    })
        .from(educationInstitutionsMinedu)
        .where(and(...andConditions))
        .limit(10);

    console.log(`Results for split '%gran%' AND '%unidad%':`, res2.length);
    if (res2.length > 0) console.log(res2);

    process.exit(0);
}

check().catch(console.error);
